# -*- coding: utf-8 -*-
"""Saving Plot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTPVcAWPZ4wEEOIpXQgu_qDfZYmhsZzI
"""

import matplotlib.pyplot as plt
import numpy as np

x_view=[202,121,312,514,212,123,454,546]
y_view=[221,421,512,554,312,523,354,246]
z_view=[222,421,316,214,712,623,354,446]

plt.figure(figsize=(10,4))
plt.plot(x_view,label='X',color='blue',linestyle='--',marker='o')
plt.plot(y_view,label='Y',color='orange',linestyle='--',marker='o')
plt.plot(z_view,label='Z',color='green',linestyle='--',marker='o')
plt.xlim(1,4)
plt.ylim(100,550)
plt.grid(True,linewidth=1,color='black',linestyle='-.')
plt.xlabel('Hari')
plt.ylabel('Angka')
plt.legend()
plt.title('Learning Matplotlib')
plt.savefig('/content/plot.png',dpi=500)  # facecolor='blue'
plt.show()

