# -*- coding: utf-8 -*-
"""HeatMap

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTPVcAWPZ4wEEOIpXQgu_qDfZYmhsZzI
"""

import seaborn as sns

sns.get_dataset_names()

titanic=sns.load_dataset('titanic')
titanic

titanic=titanic.select_dtypes('int')
titanic.corr()

sns.heatmap(titanic.corr(),annot=True,cmap='YlGnBu')

sns.heatmap(titanic.corr(),annot=True,cmap='coolwarm')

