# -*- coding: utf-8 -*-
"""Histogram

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTPVcAWPZ4wEEOIpXQgu_qDfZYmhsZzI
"""

import seaborn as sns

sns.get_dataset_names()

iris=sns.load_dataset('iris')
tips=sns.load_dataset('tips')
iris

tips

x_view=[202,121,312,514,202,121,121]

sns.histplot(x_view,bins=10)

sns.histplot(x_view,kde=True,bins=10)

sns.histplot(tips['tip'],kde='True',bins=10)

